name: test install and code all
on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.6, 3.7, 3.8, 3.9]
        package-manager: [poetry, virtualenv]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-
      - name: Install imagine
        run: npm install -g imagine
      - name: use package manager ${{ matrix.package-manager}}
        run: ./manager.sh ${{ matrix.package-manager}}
      - name: Generate code
        run: imagine compile todo.im
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: echo package manager
        run: less todo.im | grep package-manager
      - name: install package manager and dependencies
        run: make install
      - name: Lint the files
        run: make lint
      - name: run coverage
        run: make coverage
